### ISSUE TITLE
[Bug]: ATM 10 2.25 - Assembler will not make Quantum Circuit Board

### ISSUE THREAD

**Issue by LordILarrion** [AllTheMods/ATM-10#2010]
### Possible Fixes

Yes

### Modpack Version

2.25

### What happened?

Modern Industrialization Assembler will not make Quantum Circuit Board. With no locked pattern putting the supplies into the assembler creates Superconductor coil, locking the pattern and output does not work. Selecting the recipe from the assembler menu list inserts the Modern Industrialization Iridium Plate version instead of the AllTheOres version. Even using give command to get the Modern Industrialization version of the Iridium plate to insert into the assembler does not make it work.

Even tried adding a modified recipe to kubjs as suggested in another post and restarting the server. Assembler will not create the Quantum Circuit Board given all the correct supplies.

**Comment by Malefic007** [comment]
This was a pain for me too because it wanted to auto make superconductor coils like you and I was on that version before going to 2.3.  Locking is the key but, you also need an upgrade of at least +32 eu/t added to the assembler which would be 2 advanced upgrades (+16 eu/t each) or better.

**Comment by LordILarrion** [comment]
Was using 5 turbo upgrades, turbo machine hull, and overdrive, with recipe locked and wasn't working on 2.25. Updated to 2.31 and it was still trying to make the superconductor coils. Deleted/unlocked the recipe, and re-added the recipe, and it is now working.. thanks. This still need to be fixed at the Modpack level though.

**Comment by rhullah** [comment]
I'm on 2.32 and was not able to get this working using the previous suggestions. The only way I got it working was to ensure I had the proper upgrades and then lock **only** the output slots with one of them being the Quantum Circuit Board.

<img width="414" alt="Image" src="https://github.com/user-attachments/assets/018b9597-5bfb-4ff7-a878-bc7409b52edb" />

**Comment by xtended2l** [comment]
Never had issues with this. Implosion Compressor is giving me right version of iridium plates:
![Image](https://github.com/user-attachments/assets/5d39e42b-0def-4790-b42b-e4e0eec15952)
But I never used it tbh, as it is way easier and more cost-effective to set up 2-3 metal presses(immersive engineering):
![Image](https://github.com/user-attachments/assets/58bb4fd6-6524-43b1-b9c7-4e2316be8d86)
which works like a charm for me from december releases of the modpack.

![Image](https://github.com/user-attachments/assets/44aecbfa-4f80-497e-86ab-f50c72c84ca4)
But tbh I dont remember if inserting the recipe from JEI was wrong initially and I just corrected ti by dragging right components, or it was working from the start. I remember there was a lot of such issues with mekanism machines and some magic mods, becuase of nbt differences in JEI stock recipe items and items which actually crafted in the end. But do not remember if I had such issues with MI tbh.

**Comment by xtended2l** [comment]
Ok I tested whole process again:
Implosion Compressor is creating AllTheOres version of iridium plates, so no issues here.
Insertion of the recipe from JEI into the assembler actually uses wrong version of the plate:
![Image](https://github.com/user-attachments/assets/ced81b84-d365-4158-9029-ca5fc2a18972)

So all you have to do is to click on the lock(top right corner) to allow recipe editing, and replace the iridium plate with the correct one:
![Image](https://github.com/user-attachments/assets/668b6a27-322a-4cb9-a807-7f0cc814d8e3)

 This is pure JEI recipe issue, which can be considered bug, but not as critical tbh. Hope this helps.

**Comment by Krutontar** [comment]
2.38 and still an issue.  Freshly set up so no lingering programming from an early version.
